version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    vendor: true
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "composer"
    labels:
      - "type: refactoring ♻️"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/panel"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "type: refactoring ♻️"
    open-pull-requests-limit: 10
