language: php
os: linux
dist: bionic
sudo: false
services:
  - memcached

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - echo yes | pecl install -f apcu
  - echo yes | pecl install -f memcached
  - phpenv config-rm xdebug.ini || true
  - phpenv config-add tests/php.ini

install:
  # ensure that the Composer config is valid
  - composer validate

  # install Composer packages, will also trigger dump-autoload
  - composer require --no-interaction --ignore-platform-reqs "phpunit/phpunit:^7" "friendsofphp/php-cs-fixer" "pcov/clobber"
  - composer install --no-interaction --ignore-platform-reqs --no-suggest

  # install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

before_script:
  - pecl install pcov
  - mkdir -p build/logs
  - ls -al

script:
  - php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix --config .php_cs --verbose --diff --dry-run

after_success:
  - travis_retry php php-coveralls.phar -v

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - vendor

matrix:
  fast_finish: true
