name: field.blocks.heading.name
icon: title
wysiwyg: true
preview: heading
fields:
  level:
    label: field.blocks.heading.level
    type: toggles
    empty: false
    default: "h2"
    labels: false
    options:
      - value: h1
        icon: h1
      - value: h2
        icon: h2
      - value: h3
        icon: h3
      - value: h4
        icon: h4
      - value: h5
        icon: h5
      - value: h6
        icon: h6
  text:
    label: field.blocks.heading.text
    type: writer
    inline: true
    placeholder: field.blocks.heading.placeholder
