name: CI
on: [push, pull_request]

jobs:
  backend-tests:
    name: "Backend: Unit tests - PHP ${{ matrix.php }}"

    # if on pull request, only run if from a fork
    # (our own repo is covered by the push event)
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]
    env:
      extensions: mbstring, ctype, curl, gd, apcu, memcached
      ini: apc.enabled=1, apc.enable_cli=1, pcov.directory=., "pcov.exclude=\"~(vendor|tests)~\""

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2
        with:
          fetch-depth: 2

      - name: Preparations
        run: mkdir sarif

      - name: Install memcached
        uses: niden/actions-memcached@3b3ecd9d0d035ea92db716dc1540a7dbe9e56349 # pin@v7

      - name: Install system locales
        run: sudo apt-get update && sudo apt-get install -y locales-all

      - name: Setup PHP cache environment
        id: ext-cache
        uses: shivammathur/cache-extensions@fe198edd1ac99a6990225b63be8f4e9c21e9a8ca # pin@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: php-v1

      - name: Cache PHP extensions
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
        with:
          path: ${{ steps.ext-cache.outputs.dir }}
          key: ${{ steps.ext-cache.outputs.key }}
          restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP environment
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a # pin@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: ${{ env.ini }}
          coverage: pcov
          tools: phpunit:9.5.10, psalm:4.11.2

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Cache analysis data
        id: finishPrepare
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
        with:
          path: ~/.cache/psalm
          key: backend-analysis-${{ matrix.php }}

      - name: Run tests
        if: always() && steps.finishPrepare.outcome == 'success'
        run: phpunit --coverage-clover ${{ github.workspace }}/clover.xml

      - name: Statically analyze using Psalm
        if: always() && steps.finishPrepare.outcome == 'success'
        run: psalm --output-format=github --php-version=${{ matrix.php }} --report=sarif/psalm.sarif --report-show-info=false

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # pin@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # for better reliability if the GitHub API is down
          fail_ci_if_error: true
          files: ${{ github.workspace }}/clover.xml
          flags: backend
          env_vars: PHP
        env:
          PHP: ${{ matrix.php }}

      - name: Upload code scanning results to GitHub
        if: always() && steps.finishPrepare.outcome == 'success'
        uses: github/codeql-action/upload-sarif@2b46439dd5477d8a1659811cdc500d35e601a1cb # pin@v1
        with:
          sarif_file: sarif

  frontend-tests:
    name: "Frontend: Unit tests"

    # if on pull request, only run if from a fork
    # (our own repo is covered by the push event)
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Set up Node.js problem matchers and cache npm dependencies
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # pin@v2
        with:
          cache: 'npm'
          cache-dependency-path: panel/package-lock.json

      - name: Install npm dependencies
        id: finishPrepare
        run: npm ci
        working-directory: panel

      - name: Run JavaScript unit tests
        if: always() && steps.finishPrepare.outcome == 'success'
        run: npm run test:unit:coverage
        working-directory: panel

      # TODO: Disabled until Vitest coverage reporting is accurate and
      #       Kirby's frontend tests are useful enough that we need this metric
      # - name: Upload coverage results to Codecov
      #   uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # pin@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # for better reliability if the GitHub API is down
      #     fail_ci_if_error: true
      #     files: ${{ github.workspace }}/panel/coverage/lcov.info
      #     flags: frontend

  frontend-e2e:
    name: "Frontend: E2E tests"

    # if on pull request, only run if from a fork
    # (our own repo is covered by the push event)
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      php: "8.0"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2
        with:
          path: kirby

      - name: Checkout Sandbox
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2
        with:
          repository: getkirby/sandbox
          path: sandbox
          submodules: true

      - name: Preparations
        run: |
          # set up log directory
          mkdir -p ${{ github.workspace }}/_logs

          # link Kirby to Sandbox
          rm -rf ${{ github.workspace }}/sandbox/kirby
          ln -s ${{ github.workspace }}/kirby ${{ github.workspace }}/sandbox/kirby

      - name: Setup PHP cache environment
        id: ext-cache
        uses: shivammathur/cache-extensions@fe198edd1ac99a6990225b63be8f4e9c21e9a8ca # pin@v1
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          key: e2e-v1

      - name: Cache PHP extensions
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
        with:
          path: ${{ steps.ext-cache.outputs.dir }}
          key: ${{ steps.ext-cache.outputs.key }}
          restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP environment
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a # pin@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Install dependencies
        uses: cypress-io/github-action@f5bea478b80a774068179089247f13d60abc5010 # pin@v2
        with:
          working-directory: kirby/panel
          runTests: false

      - name: Build Panel dist files
        run: npm run build
        working-directory: kirby/panel

      - name: Start the PHP server
        run: php -S 127.0.0.1:8000 -t ${{ github.workspace }}/sandbox/public ${{ github.workspace }}/sandbox/router.php &> ${{ github.workspace }}/_logs/php.log &
        working-directory: kirby/panel

      - name: Run tests
        uses: cypress-io/github-action@f5bea478b80a774068179089247f13d60abc5010 # pin@v2
        with:
          working-directory: kirby/panel
          install: false
          wait-on: "http://127.0.0.1:8000/panel/login"
          wait-on-timeout: 5
          config: baseUrl=http://127.0.0.1:8000

      - name: Print log files
        if: always()
        run: |
          for log in ${{ github.workspace }}/_logs/*; do
            echo "::group::$(basename $log)"
            cat $log
            echo "::endgroup::"
          done

      - name: Archive Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # pin@v2
        with:
          name: cypress-screenshots
          path: kirby/panel/cypress/screenshots

      - name: Archive Cypress videos
        if: always()
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # pin@v2
        with:
          name: cypress-videos
          path: kirby/panel/cypress/videos

  backend-analysis:
    name: "Backend: Code Quality"

    # if on pull request, only run if from a fork
    # (our own repo is covered by the push event)
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      php: "8.0"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Preparations
        run: mkdir sarif

      - name: Setup PHP cache environment
        id: ext-cache
        uses: shivammathur/cache-extensions@fe198edd1ac99a6990225b63be8f4e9c21e9a8ca # pin@v1
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          key: php-analysis-v1

      - name: Cache PHP extensions
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
        with:
          path: ${{ steps.ext-cache.outputs.dir }}
          key: ${{ steps.ext-cache.outputs.key }}
          restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP environment
        id: finishPrepare
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a # pin@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: |
            composer:2.2.0, composer-normalize:2.18.0, composer-require-checker:4.0.0,
            composer-unused:0.7.12, phpcpd:6.0.3, phpmd:2.11.1

      - name: Validate composer.json/composer.lock
        if: always() && steps.finishPrepare.outcome == 'success'
        run: composer validate --strict --no-check-version --no-check-all

      - name: Ensure that composer.json is normalized
        if: always() && steps.finishPrepare.outcome == 'success'
        run: composer-normalize --dry-run

      - name: Check for unused Composer dependencies
        if: always() && steps.finishPrepare.outcome == 'success'
        run: composer-unused --no-progress

      - name: Check for duplicated code
        if: always() && steps.finishPrepare.outcome == 'success'
        run: phpcpd --fuzzy --exclude tests --exclude vendor .

      - name: Statically analyze using PHPMD
        if: always() && steps.finishPrepare.outcome == 'success'
        run: phpmd . github phpmd.xml.dist --exclude 'dependencies/*,tests/*,vendor/*' --reportfile-sarif sarif/phpmd.sarif

      - name: Upload code scanning results to GitHub
        if: always() && steps.finishPrepare.outcome == 'success'
        uses: github/codeql-action/upload-sarif@2b46439dd5477d8a1659811cdc500d35e601a1cb # pin@v1
        with:
          sarif_file: sarif

  coding-style:
    name: "Backend + Frontend: Coding Style"

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      php: "8.0"

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Set up Node.js problem matchers and cache npm dependencies
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # pin@v2
        with:
          cache: 'npm'
          cache-dependency-path: panel/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: panel

      - name: Setup PHP environment
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a # pin@v2
        with:
          php-version: ${{ env.php }}
          coverage: none
          tools: php-cs-fixer:3.2.1

      - name: Cache analysis data
        id: finishPrepare
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
        with:
          path: ~/.php-cs-fixer
          key: coding-style

      - name: Check for JavaScript coding style violations (ESLint)
        if: always() && steps.finishPrepare.outcome == 'success'
        # Use the --no-fix flag in push builds to get a failed CI status
        run: >
          npm run lint -- --max-warnings 0 --format stylish
          ${{ github.event_name != 'pull_request' && '--no-fix' || '' }}
        working-directory: panel

      - name: Create code suggestions from the coding style changes (on PR only)
        if: >
          always() && steps.finishPrepare.outcome == 'success' &&
          github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@c2fb8e077303cf70e9bb5bc89e8ef908c1c84d2a # pin@v1
        with:
          tool_name: ESLint
          fail_on_error: "true"

      - name: Check for JavaScript coding style violations (Prettier)
        if: always() && steps.finishPrepare.outcome == 'success'
        # Use the --check flag in push builds to get a failed CI status
        run: >
          npm run format --
          ${{ github.event_name != 'pull_request' && '--check' || '--write' }}
        working-directory: panel

      - name: Create code suggestions from the coding style changes (on PR only)
        if: >
          always() && steps.finishPrepare.outcome == 'success' &&
          github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@c2fb8e077303cf70e9bb5bc89e8ef908c1c84d2a # pin@v1
        with:
          tool_name: Prettier
          fail_on_error: "true"

      - name: Check for PHP coding style violations
        if: always() && steps.finishPrepare.outcome == 'success'
        # Use the --dry-run flag in push builds to get a failed CI status
        run: >
          php-cs-fixer fix --diff
          ${{ github.event_name != 'pull_request' && '--dry-run' || '' }}

      - name: Create code suggestions from the coding style changes (on PR only)
        if: >
          always() && steps.finishPrepare.outcome == 'success' &&
          github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@c2fb8e077303cf70e9bb5bc89e8ef908c1c84d2a # pin@v1
        with:
          tool_name: PHP-CS-Fixer
          fail_on_error: "true"
